# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15u5sNNiyNzWLmtHIevso4pMMlJC_dLR8
"""

import json
import nltk
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

with open('drive/My Drive/Colab Notebooks/bbc_articles.json') as json_file:
  json_data = json.load(json_file)
  themes = list(json_data.keys())


with open('drive/My Drive/Colab Notebooks/2017312576_이동준_TF.txt','w') as f:
  for theme in themes:
    for i in range(len(json_data[theme])):
      article = json_data[theme][i]
      f.write('('+theme+str(i+1)+")\n")
      tokens = word_tokenize(article)
      tagged_tokens = nltk.pos_tag(tokens)
      VN=dict()
      for tok, tag in tagged_tokens:
        if 'VB' in tag or 'NN' in tag :
          form = tok+'/'+tag
          if not form in VN.keys():
            VN[form] = 1
          else:
            VN[form] = VN[form] + 1
      VN_key = list(VN.keys())
      VN_key.sort(key=str.lower)
      for form in VN_key:
        f.write(form+'\t'+"TF:"+str(VN[form])+'\n')
      if theme != themes[2] or i!=99:
        f.write("\n")

