# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cPZKk_Et3QiUmTBCocixWyZFfHghGBGb
"""

import json
import nltk
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

with open('drive/My Drive/Colab Notebooks/bbc_articles.json') as json_file:
  json_data = json.load(json_file)
  theme = list(json_data.keys())
  articles = list()
  for i in theme:
    articles = articles + json_data[i]

with open('drive/My Drive/Colab Notebooks/2017312576_이동준.txt','w') as f:

  for article in articles:
    f.write(article+"\n")
    tokens = word_tokenize(article)
    tagged_tokens = nltk.pos_tag(tokens)
    f.write(tagged_tokens[0][0]+'/'+tagged_tokens[0][1])
    for tok, tag in tagged_tokens[1:]:
      f.write('+')
      f.write(tok+'/'+tag)
    f.write("\n\n")

